x-policy: &default-policy
  restart: unless-stopped
  deploy:
    update_config:
      order: start-first
      failure_action: rollback

services:
  redis_container:
    image: redis/redis-stack:latest
    ports:
      - 6380:6379
      - 8002:8001 
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
        failure_action: rollback